CI: commonly verify OpenAPI spec, use modern node

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -10,40 +10,6 @@ permissions:
   contents: read
 
 jobs:
-  verify-swagger-json:
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: backend
-    steps:
-      - uses: actions/checkout@v4
-      - uses: astral-sh/setup-uv@v5
-        with:
-          enable-cache: true
-      - run: GENERATE_SWAGGER_ONLY="true" uv run uvicorn app.main:app
-      - run: |
-          if [[ ! -z $(git diff --name-only) ]]; then
-            echo "Error: swagger json in frontend not up to date"
-            exit 1
-          fi
-
-  verify-swagger-api:
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: frontend
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-node@v4
-        with:
-          enable-cache: true
-      - run: npm run generate-api
-      - run: |
-          if [[ ! -z $(git diff --name-only) ]]; then
-            echo "Error: swagger client codegen in frontend not up to date"
-            exit 1
-          fi
-
   check-test-build:
     runs-on: ubuntu-latest
     defaults:
@@ -55,7 +21,7 @@ jobs:
 
       - uses: actions/setup-node@v4
         with:
-          node-version: 20
+          node-version: 24
           cache: npm
           cache-dependency-path: frontend/package-lock.json
 
@@ -64,9 +30,30 @@ jobs:
       - run: npm run test
       - run: npm run build
 
+  verify-swagger-api:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: frontend
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 24
+          cache: npm
+          cache-dependency-path: frontend/package-lock.json
+
+      - run: npm run generate-api
+      - run: |
+          if [[ ! -z $(git diff --name-only) ]]; then
+            echo "Error: swagger client codegen in frontend not up to date"
+            exit 1
+          fi
+
   docker:
     name: Build & publish OCI image
-    needs: [verify-swagger-json, verify-swagger-api, check-test-build]
+    needs: [verify-swagger-api, check-test-build]
     if: github.event_name == 'push'
     runs-on: ubuntu-latest
     permissions:
